Fix implicit-int
With GCC 14 series, the following error exists:

dead_port.c:43:26: error: return type defaults to 'int' [-Wimplicit-int]
   43 | #define MAIN(argc, argv) main(argc, argv)
      |                          ^~~~
dead_port.c:50:1: note: in expansion of macro 'MAIN'
   50 | MAIN(argc, argv)
      | ^~~~

(cherry picked from commit ac98929b742d5cb22c5e076c18c7a57d7242cdcd)